server:
  port: 8089

mybatis-plus:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.wayhome.srpingbootmybatis.entity.*


logging:
  level:
    com.wayhome.srpingbootmybatis.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    url: jdbc:mysql://localhost:3306/my-test?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 180000

thread:
  pool:
    core-size: 8
    max-size : 20
    queue-capacity: 50
    name-prefix: thread-pool-